### ISSUE TITLE
Problem with restarting

### ISSUE THREAD

**Issue by Mathux** [Schlipak/Hexagon.js#2]
If I die and my time is greater than 25s (phase 2), when I restart the game I can't the triangle which indicate my position. So I can't play anymore (need to reload the page)
![screen](https://user-images.githubusercontent.com/25257425/40593961-66787a56-622c-11e8-9721-2ab913cc861c.png)
 
Otherwise, you did a great job ! :)

**Comment by Schlipak** [comment]
Hi, thanks for checking the project! I am aware of this bug, but am quite unsure what caused this. In any case, this project is pretty much dead at this point, and if I ever come back to it, I might just restart from scratch, the code is really really bad 😂

**Comment by Mathux** [comment]
Ok I see ^^
